routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
//Route::get('/', function () {
//    return view('welcome');
//});

// User
use App\Product;

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Auth::routes(['verify' => true]);
        Route::get('/', 'HomeController@index');
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/category/{id}', 'HomeController@category')->name('front.category');
        Route::get('/section/{id}', 'HomeController@section')->name('front.section');
        Route::get('/product/{id}', 'HomeController@product')->name('front.product');

        Route::group([
            'middleware' => ['auth']
        ], function () {
            Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

            // User Profile
            Route::get('/user/profile', 'ProfileController@showProfile')->name('user.profile.show');
            Route::put('/user/name/save', 'ProfileController@userNameSave')->name('user.name.save');
            Route::put('/user/type/save', 'ProfileController@userTypeSave')->name('user.type.save');
            Route::put('/user/email/save', 'ProfileController@userEmailSave')->name('user.email.save');
            Route::put('/user/tel/save', 'ProfileController@userTelSave')->name('user.tel.save');
            Route::put('/user/image/save', 'ProfileController@userImageSave')->name('user.image.save');

            // User favourites
            Route::get('/user/favourites', 'FavouriteController@get')->name('user.favourites.get');
            Route::post('/user/favourites/', 'FavouriteController@add')->name('user.favourites.add');
            Route::delete('/user/favourites/delete', 'FavouriteController@delete')->name('user.favourites.delete');

            // User Products
            Route::get('/user/products', 'ProductController@index')->name('user.products.index');
            Route::delete('/user/products/delete', 'ProductController@delete')->name('user.products.delete');
            Route::get('/products/create-product', 'ProductController@startCreation')->name('user.products.start-creation');
            Route::get('/products/create/{category}', 'ProductController@create')->name('user.products.create');
            Route::post('/products/create/store', 'ProductController@storeUpdate')->name('user.products.storeUpdate');
                // User Products Create Image Dropzone
                Route::post('/products/create/dropzone-upload-image', 'ProductController@dropzoneUploadProductImage')->name('dropzone-upload-product-image');
                Route::post('/products/create/dropzone-delete-image', 'ProductController@dropzoneDeleteProductImage')->name('dropzone-delete-product-image');
                Route::get('/products/edit/dropzone-get-images', 'ProductController@dropzoneGetProductImages')->name('dropzone-get-product-images');
                Route::get('/products/{product}/edit', 'ProductController@edit')->name('user.products.edit.form');

            // Chat
            Route::get('/chat', 'ChatController@index')->name('chat.index');
            Route::get('/chat-contacts', 'ChatController@getContacts')->name('chat.contacts');
            Route::get('/chat-conversation/{id}', 'ChatController@getMessagesFor')->name('chat.get-messages-for');
            Route::post('/chat/send', 'ChatController@send')->name('chat.send');
        });
    });

//Route::post('/chat-send', 'ChatController@send')->name('chat.send');

// Admin
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('/fields', 'Admin\FieldController');
    Route::resource('/categories', 'Admin\CategoryController');

    Route::get('/categories/{category}/sections/', 'Admin\CategoryController@categorySections')->name('admin.category-sections');
    Route::get('/sections/{section}/products', 'Admin\ProductController@sectionProducts')->name('admin.section-products');

    Route::resource('/products', 'Admin\ProductController');

    Route::get('/profile', 'Admin\ProfileController@index')->name('profile.index');
    Route::put('/profile/update-data', 'Admin\ProfileController@updateData')->name('profile.update-data');
    Route::put('/profile/update-password', 'Admin\ProfileController@updatePassword')->name('profile.update-password');
    Route::get('/categories/fields/get', 'Admin\CategoryController@ajaxCategories')->name('categories.fields');
//    Route::get('/search', 'Admin\ProductController@search')->name('products.search');
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Image;
use App\Product;
use App\Attribute;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use function Sodium\add;

class ProductController extends Controller
{

    public function __construct()
    {
//        $this->photos_path = public_path('/img/products/'. date("Y/m") .'/');
//
//        if( ! File::exists($this->photos_path))
//            File::makeDirectory($this->photos_path, 0777, true);

//        if( ! File::exists($this->thumbnail_photos_path))
//            File::makeDirectory($this->thumbnail_photos_path, 0777, true);
    }

    public function index()
    {
        $products = Product::with(['category', 'lastImage'])
            ->paginate(10);

        return view('admin.pages.products.index', compact('products'));
    }

    public function sectionProducts($section_id)
    {
        $section = Category::findOrFail($section_id);

        $products = $section
            ->products()
            ->with(['mainImage', 'fields'])
            ->paginate(10);

    //     foreach ($products as $key => $product) {
    //         foreach ($product->attributes as $attr) {
    // //                echo "<pre>";
    // //                dump($attr);
    // //                echo "</pre>";
    //             $product->setAttribute($attr->title, $attr->value);
    //         }
    //     }


        // $products[0]->setAttribute('asdasd', 'sadasd');
        // dd($products[0]);

        return view('admin.pages.products.section-products', compact(['products', 'section']));
    }

    public function create()
    {
        $categories = Category::with(['fields'])
            ->where('parent_id', null)
            ->get();

        return view('admin.pages.products.new', compact('categories'));
    }

    public function stores(Request $request)
    {
//        dd($request->input('additional_fields'));
        $additionalFields = request()->input('additional_fields');
        $additionalFields[] = 'image';
        $additionalFields[] = 'additional_fields';

        $this->validate($request,[
            'title' => 'required',
            'tel' => 'required',
            'status' => 'required',
            'currency' => 'required',
            'price' => 'numeric',
            'category' => 'numeric',
            'image'=>'required|image|mimes:png,jpg,jpeg|max:1000'
        ]);

        $formInput=$request->except($additionalFields);

        if($request->file('image')) {
            $image = $request->file('image');
            if($image->isValid()){
                $filename = str_random(10);
                $extension = $image->getClientOriginalExtension();
                $fileNameToStore = $filename.'_'.time().'.'.$extension;
                $smallThumbnail = $filename.'_small_'.time().'.'.$extension;

                $large_image_path= $this->photos_path . $fileNameToStore;
                $small_image_path=$this->photos_path . $smallThumbnail;

                //Resize Image
                Image::make($image)->save($large_image_path);
                Image::make($image)->resize(300,300)->save($small_image_path);
                $formInput['img']=$fileNameToStore;
                $formInput['resized']=$smallThumbnail;
            }
        }

        $product = Product::create($formInput);



        foreach (request()->input('additional_fields') as $fieldName) {
            $productAttributes = new Attribute;
            $productAttributes->product_id = $product->id;
            $productAttributes->title = $fieldName;
            $productAttributes->value = $request->input($fieldName);
            $productAttributes->save();
        }





        return redirect()->route('product.create')->with('message','Add Products Successfully!');
    }

    // Admin store product
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'address_address'=>'required',
            'tel' => 'required',
            'status' => 'required',
            'price' => 'numeric',
            'category_id' => 'required',
            'currency' => 'required',
            'description' => 'required',
            'image' => 'required',
            'image.*' => 'image|mimes:png,jpg,jpeg,bmp|max:110000',
        ]);

        if ( ! $product = Product::add($request))
            return false;

        if ($request->hasFile('image'))
            Image::uploadImages($request->file('image'), $product->id);

        return redirect()
            ->route('products.index')
            ->with('success', 'Item created successfully!');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $product = Product::find($id);
        return view('admin.pages.products.edit', compact('product'));
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        $product = Product::findOrFail($id);

//        if ($product->user != Auth::user())
//            abort('403', 'You are not allowed to delete this product');

        $images = $product->images;

        foreach ($images as $image) {
            if (File::isFile(public_path('img/products/') . $image->original_path)) {
                File::delete(public_path('img/products/') . $image->original_path);
            }

            if (File::isFile(public_path('img/products/') . $image->resized_path)) {
                File::delete(public_path('img/products/') . $image->resized_path);
            }
        }

        $product->images()->delete();
        $product->delete();

        return redirect()->back()->with('success', 'Product Deleted');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Attribute;
use App\Category;
use App\Field;
use App\Image;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Response;
use Validator;

class ProductController extends Controller
{

    public function index()
    {
        $products = auth()->user()->products()->where('published', 1)->with(['images'])->get();
        return view('front.pages.user.products', compact('products'));
    }

    public function getUnpublishedProduct()
    {
        if ( ! $unpublished = auth()->user()->products()->where('published', 0)->first()) {

            $unpublished = Product::create([
                'title' => 'tmp',
                'description' => 'tmp',
                'price' => 0,
                'user_id' => auth()->id(),
                'tel' => auth()->user()->tel,
                'address_address' => 'auth()->user()->address_address',
                'status' => 'inactive',
                'published' => 0
            ]);
        }

        Product::removeProductImages($unpublished);

        return $unpublished;
    }

    public function create($category_id)
    {
        $product = $this->getUnpublishedProduct();
        Product::removeProductImages($product);

        if ( ! auth()->id() === $product->user_id)
            abort('403', 'You are not allowed to edit this product');

        $category = Category::findOrFail($category_id)->load('fields');
        $fields = $category->fields;

        return view('front.pages.user.product-create-form', [
            'category' => $category,
            'product' => $product,
            'fields' => $fields
        ]);
    }

    public function startCreation()
    {
        return view('front.pages.user.select-category');
    }

    public function edit($product)
    {
        $product = Product::findOrFail($product);

        if ( ! auth()->id() === $product->user_id)
            abort('403', 'You are not allowed to edit this product');

        $category = Category::findOrFail($product->category->id);
        $fields = $product->fields;

        return view('front.pages.user.product-edit-form', [
            'category' => $category,
            'product' => $product,
            'fields' => $fields
        ]);
    }

    public function storeUpdate(Request $request)
    {
        $rules = [
            'title'=>'required',
//            'address_address'=>'required',
            'tel'=>'required',
//            'status'=>'required',
            'price'=>'required',
            'category_id' => 'required',
            'currency' => 'required',
            'product_id' => 'required',
            'description'=>'required',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails())
            return back()->withErrors($validator->errors());

        $product = Product::findOrFail($request->input('product_id'));

        if ( ! $product->updateProduct($request))
            return false;

        if ( ! empty($request->input('images_order')))
            $this->sortImages(json_decode($request->input('images_order')));

        return redirect()->route('user.products.index');
    }

    public function dropzoneUploadProductImage(Request $request)
    {
        //        $rules = array(
        //            'file' => 'image|max:30000',
        //        );
        //
        //        $validation = Validator::make($request->file('file'), $rules);
        //
        //        if ($validation->fails())
        //            return Response::make($validation->errors->first(), 400);


        $id = Image::uploadImage($request->file('file'), $request->product_id);
        return response()->json(['success' => 200, 'id' => $id]);
    }

    public function dropzoneGetProductImages(Request $request)
    {
        $product_id = $request->product_id;
        $product = Product::findOrFail($product_id);
        $product->load('images');

        $images = $product->images()->orderBy('border', 'asc')->get();

        $imagesArray = [];
        foreach ($images as $image) {
            $filePath = public_path('/img/products/') . $image->resized_path;

            $imagesArray[] = [
                'name' => $image->id,
                'size' => File::size($filePath),
                'path' => '/img/products/' . $image->resized_path
            ];
        }

        return response()->json($imagesArray);
    }

    public function dropzoneDeleteProductImage(Request $request)
    {
        $id = $request->get('id');
        $image = Image::findOrFail($id);

        if (file_exists(public_path('img/products/') . $image->original_path)) {
            unlink(public_path('img/products/') . $image->original_path);
        }

        if (file_exists(public_path('img/products/') . $image->resized_path)) {
            unlink(public_path('img/products/') . $image->resized_path);
        }

        $image->delete();

        return $id;
    }

//    public function postCreateStep3(Request $request)
//    {
//
//        $validatedData = $request->validate([
//            'category_id' => 'category_id',
//            'title' => 'required',
//            'price' => 'required|numeric',
//            'tel' => 'required',
//            'description' => 'required',
//        ]);
//
//        if(empty($request->session()->get('product'))){
//            $product = new Product();
//            $product->fill($validatedData);
//            $request->session()->put('product', $product);
//        }else{
//            $product = $request->session()->get('product');
//            $product->fill($validatedData);
//            $request->session()->put('product', $product);
//        }
//
//        return redirect()->route('user.products.create-step-4');
//    }

    public function destroy($id)
    {
        $product = Product::findOrFail($id);

        if ($product->user != auth()->user())
            abort('403', 'You are not allowed to delete this product');

        Product::removeProduct($product);

        return redirect()->back()->with('success', 'Product Deleted');
    }

    public function sortImages($images_order)
    {
        foreach ($images_order as $orderData) {
            foreach ($orderData as $obj) {
                $img = Image::find($obj->id);
                $img->border = $obj->order;
                $img->save();
            }
        }
    }
}

resources/views/admin/pages/products/index.blade.php
@extends('admin.layouts.main')

@section('content')


    <div class="row form-group">
        <div class="col-xs-4">

            <form action="" method="GET" role="search">
                <div class="input-group custom-search-form">
                    <input type="search" class="form-control" name="q" placeholder="Search...">

                    <span class="input-group-btn">
                        <button class="btn btn-default-sm" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">

            @include('admin.partials.flash-messages')

            <div class="panel panel-primary">
                <div class="panel-heading">
                    Panel heading
                </div>

                <!-- Table -->
                <table id="datatable" class="table table-condensed table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Category</th>
                        <th>image</th>
                        <th>Attributes</th>
                        <th>Created_at</th>
                        <th>Updated_at</th>
                        <th>Actions</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td>{{$product->id}}</td>
                            <td>{{$product->title}}</td>
                            <td>{{$product->description}}</td>
                            <td>{{$product->category->title_en}}</td>
                            <td><img width="40" src="{{ asset('img/products/' . $product->mainImage->resized_path ?? '') }}"></td>
                            <td>
                                @if( count($product->fields) > 0)
                                    <div class="btn btn-primary btn_expander" style="width: 100%">Expand</div>

                                    <div class="additional_fields" style="display: none">
                                        <table class="table table-condensed table-bordered table-striped">
                                            @foreach($product->fields as $attribute)
                                                <tr>
                                                    <td>{{ $attribute->pivot->title }}</td>
                                                    <td>{{ $attribute->pivot->value }}</td>
                                                </tr>
                                            @endforeach
                                        </table>
                                    </div>
                                @endif
                            </td>
                            <td>{{$product->created_at}}</td>
                            <td>{{$product->updated_at}}</td>
                            <td style="text-align: center;">
                                <form action="{{ route('products.destroy', $product->id) }} " method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('products.edit', $product->id)}}" class="btn btn-primary btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>

                                    <button type="submit" onclick="return confirm('Are you sure?')" class="btn-sm btn btn-danger">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="pages">
                    {{--                        {{ $products->appends(Request::Input())->links() }}--}}
                    {{--                        {{ $products->appends(Request::except(['page']))->render() }}--}}
                    {!! $products->render() !!}
                </div>
            </div>

        </div>
    </div>




    {{--    <div class="ajax-load text-center" style="display:none">--}}
    {{--        <p><img src="http://demo.itsolutionstuff.com/plugin/loader.gif">Loading More post</p>--}}
    {{--    </div>--}}

    {{--    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">--}}
    {{--        <div class="modal-dialog" role="document">--}}
    {{--            <div class="modal-content">--}}
    {{--                <div class="modal-header">--}}
    {{--                    <h5 class="modal-title" id="exampleModalLabel">New message</h5>--}}
    {{--                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
    {{--                        <span aria-hidden="true">&times;</span>--}}
    {{--                    </button>--}}
    {{--                </div>--}}
    {{--                <div class="modal-body">--}}
    {{--                    <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">--}}
    {{--                        <div class="form-group">--}}
    {{--                            <label for="recipient-name" class="col-form-label">Title Armenian</label>--}}
    {{--                            <input type="text" class="form-control" id="recipient-name">--}}
    {{--                        </div>--}}

    {{--                        <div class="form-group">--}}
    {{--                            <label for="recipient-name" class="col-form-label">Title Russian</label>--}}
    {{--                            <input type="text" class="form-control" id="recipient-name">--}}
    {{--                        </div>--}}

    {{--                        <div class="form-group">--}}
    {{--                            <label for="recipient-name" class="col-form-label">Title English</label>--}}
    {{--                            <input type="text" class="form-control" id="recipient-name">--}}
    {{--                        </div>--}}

    {{--                        <div class="form-group">--}}
    {{--                            <label for="recipient-name" class="col-form-label">Price</label>--}}
    {{--                            <input type="text" class="form-control" id="recipient-name">--}}
    {{--                        </div>--}}

    {{--                        <div class="form-group">--}}
    {{--                            <label>Category</label>--}}
    {{--                            <select class="form-control" name="name">--}}
    {{--                                @foreach($categories as $category)--}}
    {{--                                  <option value="{{ $category->id}}">{{ $category->title_AM }}</option>--}}
    {{--                                @endforeach--}}
    {{--                            </select>--}}
    {{--                        </div>--}}

    {{--                        <div class="form-group">--}}
    {{--                            <label for="images" class="col-form-label">images</label>--}}
    {{--                            <input type="file" class="form-control" multiple name="images[]" id="images">--}}
    {{--                        </div>--}}


    {{--                    </form>--}}
    {{--                </div>--}}

    {{--                <div class="modal-footer">--}}
    {{--                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>--}}
    {{--                    <input type="submit" class="btn btn-primary" value="Submit">--}}
    {{--                </div>--}}
    {{--            </div>--}}
    {{--        </div>--}}
    {{--    </div>--}}

@endsection


@push('styles')
    <style>
        .ajax-load{
            background: #e1e1e1;
            padding: 10px 0px;
            width: 100%;
        }
    </style>
    <!-- DataTables -->
    {{--    <link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">--}}
@endpush

@push('scripts')
    <!-- DataTables -->
    {{--    <script src="{{ asset('assets/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>--}}
    {{--    <script src="{{ asset('assets/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>--}}
    {{--    <!-- SlimScroll -->--}}
    {{--    <script src="{{ asset('assets/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>--}}
    {{--    <!-- FastClick -->--}}
    {{--    <script src="{{ asset('assets/adminlte/bower_components/fastclick/lib/fastclick.js') }}"></script>--}}

    {{--    <!-- AdminLTE for demo purposes -->--}}
    {{--    <script src="{{ asset('assets/adminlte/dist/js/demo.js') }}"></script>--}}
    {{--    <!-- page script -->--}}
    {{--    <script>--}}
    {{--        $(function() {--}}
    {{--            $('#example2').DataTable({--}}
    {{--                processing: true,--}}
    {{--                serverSide: true,--}}
    {{--                ajax: '{!! route('datatables.data') !!}',--}}
    {{--                columns: [--}}
    {{--                    { data: 'id', name: 'id' },--}}
    {{--                    { data: 'title', name: 'title' },--}}
    {{--                    { data: 'category', name: 'category' },--}}
    {{--                    { data: 'image', name: 'image' },--}}
    {{--                    { data: 'created_at', name: 'created_at' },--}}
    {{--                    { data: 'updated_at', name: 'updated_at' }--}}
    {{--                ]--}}
    {{--            });--}}
    {{--        });--}}
    {{--    </script>--}}

    <script>
        $(document).ready(function() {

            $(document).on('click', '.btn_expander', function () {
                //getting the next element
                let toggle = $(this);
                content = toggle.next();
                content.toggle('slow', function () {
                        toggle.text(function () {
                            //change text based on condition
                            return content.is(":visible") ? "Collapse" : "Expand";
                        });
                    });

                // $('.majorpoints').click(function(){
                //     $(this).find('.hider').toggle();
                // });
            });

        });
    </script>

@endpush