routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
//Route::get('/', function () {
//    return view('welcome');
//});

// User
use App\Product;

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Auth::routes(['verify' => true]);
        Route::get('/', 'HomeController@index');
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/category/{id}', 'HomeController@category')->name('front.category');
        Route::get('/section/{id}', 'HomeController@section')->name('front.section');
        Route::get('/product/{id}', 'HomeController@product')->name('front.product');

        Route::group([
            'middleware' => ['auth']
        ], function () {
            Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

            // User Profile
            Route::get('/user/profile', 'ProfileController@showProfile')->name('user.profile.show');
            Route::put('/user/name/save', 'ProfileController@userNameSave')->name('user.name.save');
            Route::put('/user/type/save', 'ProfileController@userTypeSave')->name('user.type.save');
            Route::put('/user/email/save', 'ProfileController@userEmailSave')->name('user.email.save');
            Route::put('/user/tel/save', 'ProfileController@userTelSave')->name('user.tel.save');
            Route::put('/user/image/save', 'ProfileController@userImageSave')->name('user.image.save');

            // User favourites
            Route::get('/user/favourites', 'FavouriteController@get')->name('user.favourites.get');
            Route::post('/user/favourites/', 'FavouriteController@add')->name('user.favourites.add');
            Route::delete('/user/favourites/delete', 'FavouriteController@delete')->name('user.favourites.delete');

            // User Products
            Route::get('/user/products', 'ProductController@index')->name('user.products.index');
            Route::delete('/user/products/delete', 'ProductController@delete')->name('user.products.delete');
            Route::get('/products/create-product', 'ProductController@startCreation')->name('user.products.start-creation');
            Route::get('/products/create/{category}', 'ProductController@create')->name('user.products.create');
            Route::post('/products/create/store', 'ProductController@storeUpdate')->name('user.products.storeUpdate');
                // User Products Create Image Dropzone
                Route::post('/products/create/dropzone-upload-image', 'ProductController@dropzoneUploadProductImage')->name('dropzone-upload-product-image');
                Route::post('/products/create/dropzone-delete-image', 'ProductController@dropzoneDeleteProductImage')->name('dropzone-delete-product-image');
                Route::get('/products/edit/dropzone-get-images', 'ProductController@dropzoneGetProductImages')->name('dropzone-get-product-images');
                Route::get('/products/{product}/edit', 'ProductController@edit')->name('user.products.edit.form');

            // Chat
            Route::get('/chat', 'ChatController@index')->name('chat.index');
            Route::get('/chat-contacts', 'ChatController@getContacts')->name('chat.contacts');
            Route::get('/chat-conversation/{id}', 'ChatController@getMessagesFor')->name('chat.get-messages-for');
            Route::post('/chat/send', 'ChatController@send')->name('chat.send');
        });
    });

//Route::post('/chat-send', 'ChatController@send')->name('chat.send');

// Admin
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('/fields', 'Admin\FieldController');
    Route::resource('/categories', 'Admin\CategoryController');

    Route::get('/categories/{category}/sections/', 'Admin\CategoryController@categorySections')->name('admin.category-sections');
    Route::get('/sections/{section}/products', 'Admin\ProductController@sectionProducts')->name('admin.section-products');

    Route::resource('/products', 'Admin\ProductController');

    Route::get('/profile', 'Admin\ProfileController@index')->name('profile.index');
    Route::put('/profile/update-data', 'Admin\ProfileController@updateData')->name('profile.update-data');
    Route::put('/profile/update-password', 'Admin\ProfileController@updatePassword')->name('profile.update-password');
    Route::get('/categories/fields/get', 'Admin\CategoryController@ajaxCategories')->name('categories.fields');
//    Route::get('/search', 'Admin\ProductController@search')->name('products.search');
});

app/Field.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Field extends Model
{
    protected $guarded = [];
    public $timestamps = false;

    public function categories()
    {
        return $this->belongsToMany('App\Category');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product', 'product_field')
            ->withPivot(['title', 'value']);
    }
}

app/Http/Controllers/Admin/FieldController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Field;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FieldController extends Controller
{
    public function index()
    {
        $fields = Field::all();
        return view('admin.pages.fields.index', compact('fields'));
    }

    public function create()
    {
        return view('admin.pages.fields.new');
    }

    public function store(Request $request)
    {
        $data['type'] = $request->input('type');
        $data['name'] = $request->input('name');
        $data['placeholder'] = $request->input('placeholder');
        $data['title'] = $request->input('title');

        if ($request->input('type') === 'select')
            $data['value'] = json_encode($request->input('selectValues'));
        else
            $data['placeholder'] = $request->input('placeholder');

        $field = new Field;
        $field->fill($data);
        $field->save();

        return redirect()->route('fields.create');
    }

    public function show(Field $form)
    {
        //
    }

    public function edit($id)
    {
        $field = Field::findOrFail($id);
        return view('admin.pages.fields.edit', compact('field'));
    }

    public function update(Request $request, $id)
    {

        $field = Field::findOrFail($id);

        $data['type'] = $request->input('type');
        $data['name'] = $request->input('name');
        $data['title'] = $request->input('title');

        if ($request->input('type') === 'select')
            $data['value'] = json_encode($request->input('selectValues'));
        else
            $data['placeholder'] = $request->input('placeholder');

        $field->update($data);

        return redirect()->route('fields.index');
    }

    public function destroy(Field $form)
    {
        //
    }
}

resources/views/admin/pages/fields/edit.blade.php
@extends('admin.layouts.main')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">

                <div class="box-header with-border">
                    <h3 class="box-title">Edit Field {{ $field->title }}</h3>
                    @include('admin.partials.flash-messages')
                </div>

                <form id="myForm" role="form" action="{{ route('fields.update', $field->id) }}" enctype="multipart/form-data" method="post">
                    @csrf
                    @method('put')

                    <div class="box-body">

                        <div class="form-group row">
                            <label for="select" class="col-md-4 col-form-label text-md-right">{{ __('Type') }}</label>

                            <div class="col-md-6" id="selectField">
                                <select class="form-control" name="type" id="type-selector">
                                    <option value="text" {{$field->type === 'text' ? 'selected' : '' }}>Text</option>
                                    <option value="select" {{$field->type === 'select' ? 'selected' : '' }}>Select</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row" id="titleBlock">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Title') }}</label>

                            <div class="col-md-6" id="textField">
                                <input id="textValue"
                                       type="text"
                                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                                       name="title"
                                       value="{{$field->title }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row" id="placeholderBlock">
                            <label for="placeholder" class="col-md-4 col-form-label text-md-right">{{ __('Placeholder') }}</label>

                            <div class="col-md-6">
                                <input id="placeholderField"
                                       type="text"
                                       class="form-control{{ $errors->has('placeholder') ? ' is-invalid' : '' }}"
                                       name="placeholder"
                                       value="{{$field->placeholder }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name"
                                       type="text"
                                       class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                       name="name"
                                       value="{{$field->name }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row" id="selectBlock">
                            <label for="select-values" class="col-md-4 col-form-label text-md-right">{{ __('Select values') }}</label>

                            <div class="col-md-6">
                                <div class="table-responsive">
                                    <span id="result"></span>
                                    <table class="table table-bordered table-striped" id="user_table">
                                        <thead>
                                            <tr>
                                                <th width="35%">Title</th>
                                                <th width="30%">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>



                    </div>

                    <div class="box-footer">
                        <input type="submit" id="btn" class="btn btn-primary" value="Submit">
                    </div>

                </form>

            </div>
        </div>
    </div>
@endsection

@push('styles')
    <style>
        #selectBlock {
            display: none;
        }
    </style>
@endpush

@push('scripts')
    <script>
        $(document).ready(function(){

            if ($('#type-selector').val() === 'select')
                $('#selectBlock').show();
            else
                $('#selectBlock').hide();

            var count = 1;

            // dynamic_field(count);

            function dynamic_field(number = 0)
            {
                html = '<tr>';
                html += '<td><input type="text" name="selectValues[]" class="form-control" /></td>';
                if(number > 1)
                {
                    html += '<td><button type="button" name="remove" id="" class="btn btn-danger remove">Remove</button></td></tr>';
                    $('tbody').append(html);
                }
                else
                {
                    html += '<td><button type="button" name="add" id="add" class="btn btn-success">Add</button></td></tr>';
                    $('tbody').html(html);
                }
            }

            $(document).on('click', '#add', function(){
                count++;
                dynamic_field(count);
            });

            $(document).on('click', '.remove', function(){
                count--;
                $(this).closest("tr").remove();
            });

            let textInput = `<input id="title" type="text"
                                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="textValue"
                                       value="{{$field->title }}" required autofocus>`;

            $(document).on('change', '#type-selector', function() {
                if($(this).val() === 'select') {
                    // $("#textField").empty();
                    $("#selectBlock").show();
                    // $("#textField").parent().hide();
                    $("#placeholderField").val('').attr('disabled', 'disabled');
                    dynamic_field();
                } else {
                    $("tbody").empty();
                    $("#selectBlock").hide();
                    $("#placeholderField").val('').attr('disabled', false);
                    // $("#textField").parent().show();
                    $("#textField").html(textInput);
                }
            });

        });
    </script>
@endpush

resources/views/admin/pages/fields/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">

            @include('admin.partials.flash-messages')

            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading</div>

                <!-- Table -->
                <table id="datatable" class="table table-condensed table-bordered table-striped">
                    <thead>
                    <tr>
                        {{--                                <th>id</th>--}}
                        <th>Name</th>
                        <th>Placeholder</th>
                        <th>Type</th>
                        <th>Values</th>
                        {{--                                <th>Created_at</th>--}}
                        {{--                                <th>Updated_at</th>--}}
                        <th width="15%">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($fields as $field)
                        <tr>
                            <td>{{ $field->name }}</td>
                            <td>{{ $field->placeholder }}</td>
                            <td>{{ $field->type }}</td>
                            {{--                                        <td>{!! json_decode($field->value) or '' !!}</td>--}}
                            {{--                                        {{ dd(implode(', ', json_decode($field->value)) ) }}--}}
                            @if($field->type === 'select')
                                <td>{{ implode(', ', json_decode($field->value) ) ?? ''}}</td>
                            @else
                                <td></td>
                            @endif
                            <td style="text-align: center;">
                                <a href="{{ route('fields.edit', $field->id)}}" class="btn btn-primary btn-xs">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>

                                <a href="{{ route('fields.destroy', $field->id) }}"  class="btn btn-danger btn-xs">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <td>No fields</td>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>Rendering engine</th>
                        <th>Browser</th>
                        <th>Platform(s)</th>
                        <th>Engine version</th>
                        <th>CSS grade</th>
                    </tr>
                    </tfoot>
                </table>
            </div>

        </div>
    </div>
@endsection

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

    <style>

        #datatable_wrapper {
            margin-top: 15px;
        }

        ul.nav.nav-tabs li:not(.active) a {
            background-color: #eeeeee;
            color: grey;
        }

        ul.nav.nav-tabs li.active a {
            border-top: 3px solid #16a765;
        }
    </style>
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset('assets/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/adminlte/bower_components/fastclick/lib/fastclick.js') }}"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/adminlte/dist/js/demo.js') }}"></script>
    
@endpush

resources/views/admin/pages/fields/new.blade.php
@extends('admin.layouts.main')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">

                <div class="box-header with-border">
                    <h3 class="box-title">New Field</h3>
                    @include('admin.partials.flash-messages')
                </div>

                <form id="myForm" role="form" action="{{ route('fields.store') }}" enctype="multipart/form-data" method="post">
                    @csrf
                    <div class="box-body">

                        <div class="form-group row">
                            <label for="select" class="col-md-4 col-form-label text-md-right">{{ __('Type') }}</label>

                            <div class="col-md-6" id="selectField">
                                <select class="form-control" name="type" id="type-selector">
                                    <option value="text" {{ old('type') === 'text' ? 'selected' : '' }}>Text</option>
                                    <option value="select" {{ old('type') === 'select' ? 'selected' : '' }}>Select</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row" id="titleBlock">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Title') }}</label>

                            <div class="col-md-6" id="textField">
                                <input id="textValue"
                                       type="text"
                                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                                       name="title"
                                       value="{{ old('title') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row" id="placeholderBlock">
                            <label for="placeholder" class="col-md-4 col-form-label text-md-right">{{ __('Placeholder') }}</label>

                            <div class="col-md-6">
                                <input id="placeholderField"
                                       type="text"
                                       class="form-control{{ $errors->has('placeholder') ? ' is-invalid' : '' }}"
                                       name="placeholder"
                                       value="{{ old('placeholder') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name"
                                       type="text"
                                       class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                       name="name"
                                       value="{{ old('name') }}" required autofocus>
                            </div>
                        </div>

                        <div class="form-group row" id="selectBlock">
                            <label for="select-values" class="col-md-4 col-form-label text-md-right">{{ __('Select values') }}</label>

                            <div class="col-md-6">
                                <div class="table-responsive">
                                    <span id="result"></span>
                                    <table class="table table-bordered table-striped" id="user_table">
                                        <thead>
                                            <tr>
                                                <th width="35%">Title</th>
                                                <th width="30%">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>



                    </div>

                    <div class="box-footer">
                        <input type="submit" id="btn" class="btn btn-primary" value="Submit">
                    </div>

                </form>

            </div>
        </div>
    </div>
@endsection

@push('styles')
    <style>
        #selectBlock {
            display: none;
        }
    </style>
@endpush

@push('scripts')
    <script>
        $(document).ready(function(){
            let count = 1;
            let selectedType = $('#type-selector').val();
            let button, daField;

            switch (selectedType) {
                case 'select' :
                    $('#selectBlock').show();
                    break;

                case 'text' :
                    $('#selectBlock').hide();
                    break;
            }

            // dynamic_field(count);

            function dynamic_field(number = 0) {

                if(number > 1)
                    button = '<button type="button" name="remove" id="" class="btn btn-danger remove">Remove</button>';
                else
                    button = '<button type="button" name="add" id="add" class="btn btn-success">Add</button>';

                daField = $('<tr>')
                                .append($('<td>')
                                    .append($("<input name='selectValues[]' class='form-control'>")))

                                .append($('<td>')
                                    .append(button));

                $('tbody').append(daField);
            }

            $(document).on('click', '#add', function(){
                count++;
                dynamic_field(count);
            });

            $(document).on('click', '.remove', function(){
                count--;
                $(this).closest("tr").remove();
            });

            let textInput = `<input id="title" type="text"
                                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="textValue"
                                       value="{{ old('title') }}" required autofocus>`;

            $(document).on('change', '#type-selector', function() {
                count = 1;
                let fieldType = $(this).val();

                switch (fieldType) {
                    case 'select' :
                        $("#selectBlock").show();
                        $("#placeholderField").val('').attr('disabled', 'disabled');
                        dynamic_field();
                        break;

                    case 'text' :
                        $("tbody").empty();
                        $("#selectBlock").hide();
                        $("#placeholderField").val('').attr('disabled', false);
                        // $("#textField").parent().show();
                        $("#textField").html(textInput);
                        break;

                    default : alert('XZ');
                }

            });

        });
    </script>
@endpush