routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
//Route::get('/', function () {
//    return view('welcome');
//});

// User
use App\Product;

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Auth::routes(['verify' => true]);
        Route::get('/', 'HomeController@index');
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/category/{id}', 'HomeController@category')->name('front.category');
        Route::get('/section/{id}', 'HomeController@section')->name('front.section');
        Route::get('/product/{id}', 'HomeController@product')->name('front.product');

        Route::group([
            'middleware' => ['auth']
        ], function () {
            Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

            // User Profile
            Route::get('/user/profile', 'ProfileController@showProfile')->name('user.profile.show');
            Route::put('/user/name/save', 'ProfileController@userNameSave')->name('user.name.save');
            Route::put('/user/type/save', 'ProfileController@userTypeSave')->name('user.type.save');
            Route::put('/user/email/save', 'ProfileController@userEmailSave')->name('user.email.save');
            Route::put('/user/tel/save', 'ProfileController@userTelSave')->name('user.tel.save');
            Route::put('/user/image/save', 'ProfileController@userImageSave')->name('user.image.save');

            // User favourites
            Route::get('/user/favourites', 'FavouriteController@get')->name('user.favourites.get');
            Route::post('/user/favourites/', 'FavouriteController@add')->name('user.favourites.add');
            Route::delete('/user/favourites/delete', 'FavouriteController@delete')->name('user.favourites.delete');

            // User Products
            Route::get('/user/products', 'ProductController@index')->name('user.products.index');
            Route::delete('/user/products/delete', 'ProductController@delete')->name('user.products.delete');
            Route::get('/products/create-product', 'ProductController@startCreation')->name('user.products.start-creation');
            Route::get('/products/create/{category}', 'ProductController@create')->name('user.products.create');
            Route::post('/products/create/store', 'ProductController@storeUpdate')->name('user.products.storeUpdate');
                // User Products Create Image Dropzone
                Route::post('/products/create/dropzone-upload-image', 'ProductController@dropzoneUploadProductImage')->name('dropzone-upload-product-image');
                Route::post('/products/create/dropzone-delete-image', 'ProductController@dropzoneDeleteProductImage')->name('dropzone-delete-product-image');
                Route::get('/products/edit/dropzone-get-images', 'ProductController@dropzoneGetProductImages')->name('dropzone-get-product-images');
                Route::get('/products/{product}/edit', 'ProductController@edit')->name('user.products.edit.form');

            // Chat
            Route::get('/chat', 'ChatController@index')->name('chat.index');
            Route::get('/chat-contacts', 'ChatController@getContacts')->name('chat.contacts');
            Route::get('/chat-conversation/{id}', 'ChatController@getMessagesFor')->name('chat.get-messages-for');
            Route::post('/chat/send', 'ChatController@send')->name('chat.send');
        });
    });

//Route::post('/chat-send', 'ChatController@send')->name('chat.send');

// Admin
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('/fields', 'Admin\FieldController');
    Route::resource('/categories', 'Admin\CategoryController');

    Route::get('/categories/{category}/sections/', 'Admin\CategoryController@categorySections')->name('admin.category-sections');
    Route::get('/sections/{section}/products', 'Admin\ProductController@sectionProducts')->name('admin.section-products');

    Route::resource('/products', 'Admin\ProductController');

    Route::get('/profile', 'Admin\ProfileController@index')->name('profile.index');
    Route::put('/profile/update-data', 'Admin\ProfileController@updateData')->name('profile.update-data');
    Route::put('/profile/update-password', 'Admin\ProfileController@updatePassword')->name('profile.update-password');
    Route::get('/categories/fields/get', 'Admin\CategoryController@ajaxCategories')->name('categories.fields');
//    Route::get('/search', 'Admin\ProductController@search')->name('products.search');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title_am', 'title_ru', 'title_en', 'parent_id', 'image'];

    public function fields()
    {
        return $this->belongsToMany('App\Field', 'category_field');
    }

    public function sections() 
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function parent( )
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

//    public function products()
//    {
//        return $this->hasManyThrough('App\Product', 'App\Category', 'id', 'parent_id');
//    }

    public function products()
    {
        return $this->hasMany('App\Product');
    }

//----------------------------------------------------------------------------------------------------------------------
    public static function add($request)
    {
        $category = new static;
        $category->fill($request->except(['image']));

        if ($request->hasFile('image'))
            $category->image = $category->uploadImage($request->file('image'));

        $category->save();

        return $category;
    }


    public function uploadImage($image)
    {
        if ($image == null)
            return;

        $this->removeImage();

        $filename = time().'-' . str_random(10) . '.' . $image->extension();
        $image->move(public_path('img/categories/'), $filename);
        return $filename;
    }


    public function removeImage()
    {
//        if ($this->image != null)
//            Storage::delete('uploads/' . $this->img);
// Or
//        $image_path = public_path('img/categories') . $this->img;
//        if(File::exists($image_path))
//            File::delete($image_path);
//
// Or
        $image_path = public_path('img/categories/') . $this->image;
//        dd($image_path);
        if (file_exists($image_path))
            @unlink($image_path);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Field;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::where('parent_id', null)->get();
        return view('admin.pages.categories.index', compact('categories'));
    }

    public function categorySections($category_id)
    {
        $sections = Category::findOrFail($category_id)
            ->sections()
            ->where('parent_id', $category_id)
            ->with(['fields'])
            ->get();

        return view('admin.pages.categories.category-sections', compact('sections'));
    }

    public function sectionProducts($section_id)
    {
        $section = Category::findOrFail($section_id);
        $products = $section->products;

//        $products= DB::table('products')->where('category_id', $section_id)->get();

        return view('admin.pages.categories.section-products', compact('products'));
    }
    
    public function create()
    {
        $categories = Category::where('parent_id', null)->get();
        $fields = Field::all();

        return view('admin.pages.categories.new', compact(['categories', 'fields']));
    }

    public function store(Request $request)
    {
        $rules =  [
            'title_am' => 'required',
            'title_ru' => 'required',
            'title_en' => 'required',
        ];  

        if ($request->hasFile('image')) {
            $rules['image'] = 'required|image|mimes:jpeg,jpg,bmp,png,gif';
	    }

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails())
            return back()->withErrors($validator->errors());

        $category = Category::add($request);

        $fields_ids = $request->input('additional_fields');
        $category->fields()->sync($fields_ids);

        return redirect()
            ->route('categories.index')
            ->with('success', 'Category created successfully!');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $all_categories = Category::with(['parent'])->get();
        $current_category = $all_categories->find($id);
        $categories = $all_categories->where('parent_id', null);

        return view('admin.pages.categories.edit', compact(['categories', 'current_category']));
    }

    public function update(Request $request, $id)
    {
        $category=Category::findOrFail($id);

        $rules = [
            'title_am'=>'required',
            'title_ru'=>'required',
            'title_en'=>'required',
        ];

        $formInput = $request->all();

        if ($request->hasFile('image'))
            $rules['image'] = 'required|image|mimes:jpeg,jpg,bmp,png,gif';

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails())
            return back()->withErrors($validator->errors());

        if($request->hasFile('image'))
            $formInput['image'] = $category->uploadimage($request->file('image'));

        $category->update($formInput);

        return redirect()->route('categories.index')->with('success', 'Category updated');
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->removeImage();
        $category->delete();

        return redirect()->back()->with('success', 'Category deleted');
    }

//    ------------------------------------------------------------------------------------------------------------------
//    Вместо этого аякс метода можно также получить нужные дополнительные поля блэйдовым форичем без джаваскрипта
    public function ajaxCategories(Request $request)
    {
        if($request->ajax()) {
            $category = Category::find($request->category);
            $categoryFields = $category->fields;
            return response()->json(['categoryFields' => $categoryFields]);
        }
    }
}

resources/views/admin/pages/categories/categories.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">

            @include('admin.partials.flash-messages')

            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading</div>
                <!-- Table -->
                <table id="datatable" class="table table-condensed table-striped">
                    <thead>
                    <tr>
                        {{--                                <th>id</th>--}}
                        <th>Image</th>
                        <th>Title_AM</th>
                        <th>Title_RU</th>
                        <th>Title_EN</th>
                        <th>Parent</th>
                        <th width="25%">Additional Fields</th>
                        <th>Created_at</th>
                        <th>Updated_at</th>
                        <th width="15%" class="text-center">Actions</th>
                    </tr>
                    </thead>

                    <tbody>
                    @forelse($categories as $category)
                        <tr>
                            <td><img height="40px" width="40px" src="{{ asset('img/categories/' . $category->image) }}" alt=""></td>
                            <td>{{ $category->title_am }}</td>
                            <td>{{ $category->title_ru }}</td>
                            <td>{{ $category->title_en }}</td>
                            <td>{{ $category->parent->title_en ?? '' }}</td>
                            {{--                                        {{ dd($category->fields) }}--}}
                            <td>
                                @if( count($category->fields) > 0)
                                    @foreach($category->fields as $field)
                                        {{ $field->title . ', ' }}
                                    @endforeach
                                @endif
                            </td>
                            <td><a href="">{{ $category->created_at }}</a></td>
                            <td><a href="">{{ $category->updated_at}}</a></td>
                            <td style="text-align: center;">

                                <form action="{{ route('categories.destroy', $category->id) }} " method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('categories.edit', $category->id)}}" class="btn btn-primary btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>

                                    <button type="submit" onclick="return confirm('Are you sure?')" class="btn-sm btn btn-danger">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                                {{--                                    <a href="{{ route('categories.destroy', $category->id) }}"  class="btn btn-danger btn-xs">--}}
                                {{--                                        <span class="glyphicon glyphicon-trash"></span>--}}
                                {{--                                    </a>--}}
                            </td>
                        </tr>
                    @empty
                        <td>No categories</td>
                    @endforelse
                    </tbody>

                </table>
            </div>

        </div>
    </div>
@endsection

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

    <style>
        /*table th, table td {*/
        /*    text-align: center;*/
        /*}*/
    </style>
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset('assets/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/adminlte/bower_components/fastclick/lib/fastclick.js') }}"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/adminlte/dist/js/demo.js') }}"></script>
@endpush

resources/views/admin/pages/categories/category-sections.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">

            @include('admin.partials.flash-messages')

            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading</div>
                <!-- Table -->
                <table id="datatable" class="table table-condensed table-striped">
                    <thead>
                    <tr>
                        {{--                                <th>id</th>--}}
                        <th>Image</th>
                        <th>Title_AM</th>
                        <th>Title_RU</th>
                        <th>Title_EN</th>
{{--                        <th>Parent</th>--}}
                        <th width="25%">Additional Fields</th>
                        <th>Created_at</th>
                        <th>Updated_at</th>
                        <th width="15%" class="text-center">Actions</th>
                    </tr>
                    </thead>

                    <tbody>
                    @forelse($sections as $section)
                        <tr>
                            <td><a href="{{ route('admin.section-products', $section->id) }}"><img height="40px" width="40px" src="{{ asset('img/categories/' . $section->image) }}" alt=""></a></td>
                            <td><a href="{{ route('admin.section-products', $section->id) }}">{{ $section->title_am }}</a></td>
                            <td><a href="{{ route('admin.section-products', $section->id) }}">{{ $section->title_ru }}</a></td>
                            <td><a href="{{ route('admin.section-products', $section->id) }}">{{ $section->title_en }}</a></td>

{{--                            <td>{{ $section->parent->title_en ?? '' }}</td>--}}

                            <td>
                                @if( count($section->fields) > 0)
                                    {{ implode($section->fields->pluck('title')->toArray(), ', ') }}

                                    {{--Or with foreach--}}
                                    {{--@foreach($section->fields as $field)--}}
                                    {{--    {{ $field->title . ', ' }}--}}
                                    {{--@endforeach--}}

                                    {{-- Or get the values in controller and model relations, seems difficult --}}
                                @endif
                            </td>

                            <td><a href="">{{ $section->created_at }}</a></td>
                            <td><a href="">{{ $section->updated_at}}</a></td>
                            <td style="text-align: center;">

                                <form action="{{ route('categories.destroy', $section->id) }} " method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('categories.edit', $section->id)}}" class="btn btn-primary btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>

                                    <button type="submit" onclick="return confirm('Are you sure?')" class="btn-sm btn btn-danger">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                                {{--                                    <a href="{{ route('categories.destroy', $section->id) }}"  class="btn btn-danger btn-xs">--}}
                                {{--                                        <span class="glyphicon glyphicon-trash"></span>--}}
                                {{--                                    </a>--}}
                            </td>
                        </tr>
                    @empty
                        <td>No categories</td>
                    @endforelse
                    </tbody>

                </table>
            </div>

        </div>
    </div>
@endsection

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

    <style>
        td a {
            color: #000000;
            /*text-decoration: none;*/
        }
    </style>
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset('assets/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/adminlte/bower_components/fastclick/lib/fastclick.js') }}"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/adminlte/dist/js/demo.js') }}"></script>
@endpush

resources/views/admin/pages/categories/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">

                <div class="box-header with-border">
                    <h3 class="box-title">Edit Category</h3>
                </div>

                @include('admin.partials.flash-messages')

                <!-- /.box-header -->
                <!-- form start -->
                <form role="form" action="{{ route('categories.update', $current_category->id) }}" enctype="multipart/form-data" method="post">
                    @method('PUT')
                    @csrf
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputTitleArmenian">Title Armenian</label>
                            <input type="text" name="title_am" class="form-control" id="exampleInputTitleArmenian" placeholder="Enter Title" value="{{ $current_category->title_am }}">
                            <span class="text-danger">{{$errors->first('title_am')}}</span>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputTitleRussian">Title Russian</label>
                            <input type="text" name="title_ru" class="form-control" id="exampleInputTitleRussian" placeholder="Enter Title" value="{{ $current_category->title_ru }}">
                            <span class="text-danger">{{$errors->first('title_ru')}}</span>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputTitleEnglish">Title English</label>
                            <input type="text" name="title_en" class="form-control" id="exampleInputTitleEnglish" placeholder="Enter Title" value="{{ $current_category->title_en }}">
                            <span class="text-danger">{{$errors->first('title_en')}}</span>
                        </div>

{{--                        {{ dd($current_category->parent->title_en) }}--}}

                        <div class="form-group">
                            <label>Parent Category</label>
                            <select class="form-control" name="parent_id">
                                <option value="">Root</option>
{{--                                <option value="" {{ $current_category->parent_id == null ? 'selected' : '' }}>Root</option>--}}
                                @foreach($categories as $category)
                                    {{ $category->parent_id }}
                                    <option value="{{ $category->id }}" {{ $current_category->parent_id == $category->id ? 'selected' : '' }}>{{ $category->title_en }}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="control-group">
                            <label class="control-label">Image upload</label>
                            <div class="controls">
                                <input type="file" name="image" id="image"/>
                                <span class="text-danger">{{$errors->first('image')}}</span>
{{--                                @if($current_category->img != '')--}}
                                    &nbsp;&nbsp;&nbsp;
{{--<!--                                    <a href="javascript:" rel="{{$current_category->id}}" rel1="delete-image" class="btn btn-danger btn-mini deleteRecord">Delete Old Image</a>-->--}}
                                    <img src="{{asset('img/categories/' . $current_category->image)}}" width="35" alt="">
{{--                                @endif--}}
                            </div>
                        </div>

{{--                        <div class="form-group">--}}
{{--                            <label for="exampleInputFile">Icon</label>--}}
{{--                            <input type="file" name="image" id="exampleInputFile">--}}

{{--                            <p class="help-block">Example block-level help text here.</p>--}}
{{--                        </div>--}}
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <a href="{{ route('categories.index') }}" class="btn btn-default">Back</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->



        </div>
    </div>
@endsection

@push('styles')
@endpush

@push('scripts')
    <!-- SlimScroll -->
    <script src="{{ asset('assets/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/adminlte/bower_components/fastclick/lib/fastclick.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/adminlte/dist/js/demo.js') }}"></script>
@endpush

resources/views/admin/pages/categories/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-xs-12">

            @include('admin.partials.flash-messages')

            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading</div>
                <!-- Table -->
                <table id="datatable" class="table table-condensed table-striped">
                    <thead>
                    <tr>
                        {{--                                <th>id</th>--}}
                        <th>Image</th>
                        <th>Title AM</th>
                        <th>Title RU</th>
                        <th>Title EN</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                        <th width="15%" class="text-center">Actions</th>
                    </tr>
                    </thead>

                    <tbody>
                    @forelse($categories as $category)
                        <tr>
                            <td><a href="{{ route('admin.category-sections', $category->id) }}"><img height="40px" width="40px" src="{{ asset('img/categories/' . $category->image) }}" alt=""></a></td>
                            <td><a href="{{ route('admin.category-sections', $category->id) }}">{{ $category->title_am }}</a></td>
                            <td><a href="{{ route('admin.category-sections', $category->id) }}">{{ $category->title_ru }}</a></td>
                            <td><a href="{{ route('admin.category-sections', $category->id) }}">{{ $category->title_en }}</a></td>
                            <td>{{ $category->created_at }}</td>
                            <td>{{ $category->updated_at }}</td>
                            <td style="text-align: center;">

                                <form action="{{ route('categories.destroy', $category->id) }} " method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('categories.edit', $category->id)}}" class="btn btn-primary btn-sm">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>

                                    <button type="submit" onclick="return confirm('Are you sure?')" class="btn-sm btn btn-danger">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                                {{--                                    <a href="{{ route('categories.destroy', $category->id) }}"  class="btn btn-danger btn-xs">--}}
                                {{--                                        <span class="glyphicon glyphicon-trash"></span>--}}
                                {{--                                    </a>--}}
                            </td>
                        </tr>
                    @empty
                        <td>No categories</td>
                    @endforelse
                    </tbody>

                </table>
            </div>

        </div>
    </div>
@endsection

@push('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

    <style>
        td a {
            color: #000000;
            /*text-decoration: none;*/
        }
    </style>
@endpush

@push('scripts')
    <!-- DataTables -->
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset('assets/adminlte/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('assets/adminlte/bower_components/fastclick/lib/fastclick.js') }}"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/adminlte/dist/js/demo.js') }}"></script>
@endpush

resources/views/admin/pages/categories/show.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Category</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $category->title_en }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $category->description }}
            </div>
        </div>
    </div>
@endsection