routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//
//Route::get('/', function () {
//    return view('welcome');
//});

// User
use App\Product;

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Auth::routes(['verify' => true]);
        Route::get('/', 'HomeController@index');
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('/category/{id}', 'HomeController@category')->name('front.category');
        Route::get('/section/{id}', 'HomeController@section')->name('front.section');
        Route::get('/product/{id}', 'HomeController@product')->name('front.product');

        Route::group([
            'middleware' => ['auth']
        ], function () {
            Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

            // User Profile
            Route::get('/user/profile', 'ProfileController@showProfile')->name('user.profile.show');
            Route::put('/user/name/save', 'ProfileController@userNameSave')->name('user.name.save');
            Route::put('/user/type/save', 'ProfileController@userTypeSave')->name('user.type.save');
            Route::put('/user/email/save', 'ProfileController@userEmailSave')->name('user.email.save');
            Route::put('/user/tel/save', 'ProfileController@userTelSave')->name('user.tel.save');
            Route::put('/user/image/save', 'ProfileController@userImageSave')->name('user.image.save');

            // User favourites
            Route::get('/user/favourites', 'FavouriteController@get')->name('user.favourites.get');
            Route::post('/user/favourites/', 'FavouriteController@add')->name('user.favourites.add');
            Route::delete('/user/favourites/delete', 'FavouriteController@delete')->name('user.favourites.delete');

            // User Products
            Route::get('/user/products', 'ProductController@index')->name('user.products.index');
            Route::delete('/user/products/delete', 'ProductController@delete')->name('user.products.delete');
            Route::get('/products/create-product', 'ProductController@startCreation')->name('user.products.start-creation');
            Route::get('/products/create/{category}', 'ProductController@create')->name('user.products.create');
            Route::post('/products/create/store', 'ProductController@storeUpdate')->name('user.products.storeUpdate');
                // User Products Create Image Dropzone
                Route::post('/products/create/dropzone-upload-image', 'ProductController@dropzoneUploadProductImage')->name('dropzone-upload-product-image');
                Route::post('/products/create/dropzone-delete-image', 'ProductController@dropzoneDeleteProductImage')->name('dropzone-delete-product-image');
                Route::get('/products/edit/dropzone-get-images', 'ProductController@dropzoneGetProductImages')->name('dropzone-get-product-images');
                Route::get('/products/{product}/edit', 'ProductController@edit')->name('user.products.edit.form');

            // Chat
            Route::get('/chat', 'ChatController@index')->name('chat.index');
            Route::get('/chat-contacts', 'ChatController@getContacts')->name('chat.contacts');
            Route::get('/chat-conversation/{id}', 'ChatController@getMessagesFor')->name('chat.get-messages-for');
            Route::post('/chat/send', 'ChatController@send')->name('chat.send');
        });
    });

//Route::post('/chat-send', 'ChatController@send')->name('chat.send');

// Admin
Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function () {
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('/fields', 'Admin\FieldController');
    Route::resource('/categories', 'Admin\CategoryController');

    Route::get('/categories/{category}/sections/', 'Admin\CategoryController@categorySections')->name('admin.category-sections');
    Route::get('/sections/{section}/products', 'Admin\ProductController@sectionProducts')->name('admin.section-products');

    Route::resource('/products', 'Admin\ProductController');

    Route::get('/profile', 'Admin\ProfileController@index')->name('profile.index');
    Route::put('/profile/update-data', 'Admin\ProfileController@updateData')->name('profile.update-data');
    Route::put('/profile/update-password', 'Admin\ProfileController@updatePassword')->name('profile.update-password');
    Route::get('/categories/fields/get', 'Admin\CategoryController@ajaxCategories')->name('categories.fields');
//    Route::get('/search', 'Admin\ProductController@search')->name('products.search');
});

resources/views/admin/partials/_scripts.blade.php
<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{{asset('assets/adminlte/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('assets/adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('assets/adminlte/dist/js/adminlte.min.js')}}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->

{{-- Individual page scripts--}}
@stack('scripts')

resources/views/admin/partials/_styles.blade.php
<link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/font-awesome/css/font-awesome.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('assets/adminlte/bower_components/Ionicons/css/ionicons.min.css') }}">

{{--Individual pages styles--}}
@stack('styles')

<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('assets/adminlte/dist/css/AdminLTE.min.css') }}">
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
      page. However, you can choose any other skin. Make sure you
      apply the skin class to the body tag so the changes take effect. -->
{{--<link rel="stylesheet" href="{{ asset('assets/adminlte/dist/css/skins/skin-blue.min.css') }}">--}}
<link rel="stylesheet" href="{{ asset('assets/adminlte/dist/css/skins/_all-skins.min.css') }}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/admin/partials/control-sidebar.blade.php
<!-- Create the tabs -->
<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
            <li>
                <a href="javascript:;">
                    <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                    <div class="menu-info">
                        <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                        <p>Will be 23 on April 24th</p>
                    </div>
                </a>
            </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
            <li>
                <a href="javascript:;">
                    <h4 class="control-sidebar-subheading">
                        Custom Template Design
                        <span class="pull-right-container">
                <span class="label label-danger pull-right">70%</span>
              </span>
                    </h4>

                    <div class="progress progress-xxs">
                        <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                    </div>
                </a>
            </li>
        </ul>
        <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
            <h3 class="control-sidebar-heading">General Settings</h3>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    Report panel usage
                    <input type="checkbox" class="pull-right" checked>
                </label>

                <p>
                    Some information about this general settings option
                </p>
            </div>
            <!-- /.form-group -->
        </form>
    </div>
    <!-- /.tab-pane -->
</div>

resources/views/admin/partials/flash-messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if($errors->any() )
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/admin/partials/footer.blade.php
<!-- To the right -->
<div class="pull-right hidden-xs">
    Anything you want
</div>
<!-- Default to the left -->
<strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.

resources/views/admin/partials/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>@yield('title')</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

resources/views/admin/partials/header.blade.php
<!-- Logo -->
<a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
</a>

<!-- Header Navbar -->
<nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            <!-- Messages: style can be found in dropdown.less-->
            <li class="dropdown messages-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-envelope-o"></i>
                    <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 4 messages</li>
                    <li>
                        <!-- inner menu: contains the messages -->
                        <ul class="menu">
                            <li><!-- start message -->
                                <a href="#">
                                    <div class="pull-left">
                                        <!-- User Image -->
{{--                                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">--}}
                                        <img src="{{ auth()->user()->getImage() }}" class="img-circle" alt="User Image">

                                    </div>
                                    <!-- Message title and timestamp -->
                                    <h4>
                                        Support Team
                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                    </h4>
                                    <!-- The message -->
                                    <p>Why not buy a new awesome theme?</p>
                                </a>
                            </li>
                            <!-- end message -->
                        </ul>
                        <!-- /.menu -->
                    </li>
                    <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
            </li>
            <!-- /.messages-menu -->

            <!-- Notifications Menu -->
            <li class="dropdown notifications-menu">
                <!-- Menu toggle button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bell-o"></i>
                    <span class="label label-warning">{{ count($inactiveProducts) }}</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have {{ count($inactiveProducts) }} notifications</li>
                    @foreach($inactiveProducts as $inactiveProduct)
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    <a href="{{ route('products.edit', $inactiveProduct->id) }}">
                                        <i class="fa fa-users text-aqua"></i> {{ $inactiveProduct->title_en }}
                                    </a>
                                </li>
                                <!-- end notification -->
                            </ul>
                        </li>
                    @endforeach
                    <li class="footer"><a href="#">View all</a></li>
                </ul>
            </li>
            <!-- Tasks Menu -->
            <li class="dropdown tasks-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-flag-o"></i>
                    <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                    <li class="header">You have 9 tasks</li>
                    <li>
                        <!-- Inner menu: contains the tasks -->
                        <ul class="menu">
                            <li><!-- Task item -->
                                <a href="#">
                                    <!-- Task title and progress text -->
                                    <h3>
                                        Design some buttons
                                        <small class="pull-right">20%</small>
                                    </h3>
                                    <!-- The progress bar -->
                                    <div class="progress xs">
                                        <!-- Change the css width attribute to simulate progress -->
                                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <!-- end task item -->
                        </ul>
                    </li>
                    <li class="footer">
                        <a href="#">View all tasks</a>
                    </li>
                </ul>
            </li>
            <!-- User Account Menu -->
            <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <!-- The user image in the navbar-->
{{--                    <img src="{{ asset('assets/adminlte/dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image">--}}
                    <img src="{{ auth()->user()->getImage() }}" class="user-image" alt="User Image">
                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                    <span class="hidden-xs">{{ auth()->user()->name }}</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- The user image in the menu -->
                    <li class="user-header">
{{--                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">--}}
                        <img src="{{ auth()->user()->getImage() }}" class="img-circle" alt="User Image">

                        <p>
                            Alexander Pierce - Web Developer
                            <small>Member since Nov. 2012</small>
                        </p>
                    </li>
                    <!-- Menu Body -->
                    <li class="user-body">
                        <div class="row">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </div>
                        <!-- /.row -->
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <div class="pull-left">
                            <a href="{{ route('profile.index') }}" class="btn btn-default btn-flat">Profile</a>
                        </div>
                        <div class="pull-right">
                            <a href="{{ route('logout') }}" class="btn btn-default btn-flat">Sign out</a>
                        </div>
                    </li>
                </ul>
            </li>
            <!-- Control Sidebar Toggle Button -->
            <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/partials/main-sidebar.blade.php
<!-- Sidebar user panel (optional) -->
<div class="user-panel">
    <div class="pull-left image">
{{--        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">--}}
        <img src="{{ auth()->user()->getImage() }}" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
        <p>{{ auth()->user()->name }}</p>
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
</div>

<!-- search form (Optional) -->
<form action="#" method="get" class="sidebar-form">
    <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
          </button>
        </span>
    </div>
</form>
<!-- /.search form -->

<!-- Sidebar Menu -->
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->
{{--    <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Link</span></a></li>--}}
{{--    <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>--}}

    <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>Categories</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('categories.index') }}">List all categories</a></li>
            <li><a href="{{ route('categories.create') }}">Create new category</a></li>
        </ul>
    </li>

    <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>Products</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('products.index') }}">List all products</a></li>
            <li><a href="{{ route('products.create') }}">Create new product</a></li>
        </ul>
    </li>

    <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>Fields</span>
            <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="{{ route('fields.index') }}">List all fields</a></li>
            <li><a href="{{ route('fields.create') }}">Create new field</a></li>
        </ul>
    </li>
</ul>
<!-- /.sidebar-menu -->